version: '3'
services:
  vector_db_api:
    image: talgin/vectorization_mx_torch:latest
    container_name: mvd_vectorization_api
    restart: unless-stopped
    working_dir: /api_folder/app
    volumes:
      - ./:/api_folder
      - /TENGRI:/TENGRI
      - /var/run/docker.sock:/var/run/docker.sock
    # network_mode: host
    ports:
      - "20040:8887"
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: uvicorn main:app --host 0.0.0.0 --port 8887 --workers 6 --forwarded-allow-ips "*" --reload
    # command: tail -f /dev/null
    #command: sh -c "sleep 10s && uvicorn main:app --reload --host 0.0.0.0 --port 3333 --workers 10 --forwarded-allow-ips '*'"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PROJECT_SRC_RT=/api_folder
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
